### ISSUE TITLE
Trouble With Relative Paths

### ISSUE THREAD

**Issue by jmwright** [stemn/stemn-pipeline-containers#2]
I've been through the [docs](https://help.stemn.com/automation-pipelines/pipeline-configuration/input-files#multiple-relative-and-absolute-paths) a few times, and I'm still having trouble. This [pipeline](https://stemn.com/files/5b15410c252c9400192ab940/5b19f2c1b2698100194c80cf?revision=5b200d3378761f0019915675) seems to overwrite the bom.csv file in the `parts/chassis/BoM/` directory, rather than putting it in the top level `BoM/bom.csv` location as expected. I've tried a few variations, but can't seem to find the combo that works properly. The intent of the script in that pipeline is to dump all of the BoMs in the directory tree into the top level BoM file. Right now I'm using `>` which does an overwrite, but once I get the relative vs absolute path figured out I'll wipe the top level file each time and use `>>` to append.

**Comment by sabrehagen** [comment]
This is a bug on our backend. The code that checks for an existing version of the file being uploaded is at fault:
```
path: { $regex: new RegExp(`${upload.path}$`) } // TODO this regex is too loose
```

When I wrote this I hoped the collision case (triggered by both `BoM/bom.csv` and `parts/chassis/BoM/bom.csv` matching the regex) would not happen too soon. Instead it happened almost immediately :)

I will put a band-aid on this asap.

**Comment by sabrehagen** [comment]
This has been fixed. In addition to fixing this, `.pipeline` files not in the root folder operate on only their sub-directory now too. This had not been working previously. Two birds with one stone!
